"""Streamlit frontend for the tool-selection robustness harness.

A multi-page UI over the existing core modules (tool library, retriever,
selector, runner, defenses, generators) for *defensive benchmarking* of
tool-selection pipelines: measuring selection accuracy and target-* rates
under modified tool registries, and evaluating perplexity-based detection.
No attack tooling is included or generated by this app.

Run with:  streamlit run app.py
"""

from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import plotly.express as px
import streamlit as st

from tool_selection_harness.core import (
    BenchmarkRunner,
    Retriever,
    Selector,
    ToolDocument,
    ToolLibrary,
    confusion_counts,
    false_negative_rate,
    false_positive_rate,
)
from tool_selection_harness.core.defenses import (
    KnownAnswerDetector,
    PerplexityDetector,
    PerplexityWindowedDetector,
    ThresholdClassifier,
)
from tool_selection_harness.core.generators import (
    generate_task_descriptions,
    generate_tool_documents,
)
from tool_selection_harness.core.retriever import hashing_embedder

ROOT = Path(__file__).resolve().parent
SAMPLE_TOOLS = ROOT / "tool_selection_harness" / "data" / "sample_tools.json"
HISTORY_DIR = ROOT / "benchmark_history"

EMBEDDING_BACKENDS = ("MiniLM (sentence-transformers)", "Offline hashing (no download)")
LLM_PROVIDERS = ("Mock (offline)", "OpenAI", "Anthropic")

st.set_page_config(page_title="Tool-Selection Harness", layout="wide")


# ---------------------------------------------------------------------------
# Cached resources (embedding models, LLM clients, detectors)
# ---------------------------------------------------------------------------


@st.cache_resource(show_spinner=False)
def load_minilm_retriever() -> Retriever:
    """sentence-transformers all-MiniLM-L6-v2 backend (downloads on first use)."""
    return Retriever()


@st.cache_resource(show_spinner=False)
def load_offline_retriever() -> Retriever:
    """Deterministic hashing embedder; no downloads."""
    return Retriever(embed_fn=hashing_embedder())


def get_retriever(backend: str) -> Retriever:
    if backend.startswith("MiniLM"):
        return load_minilm_retriever()
    return load_offline_retriever()


@st.cache_resource(show_spinner=False)
def load_detector() -> PerplexityDetector:
    """gpt2-based perplexity detector (lazy model download on first score)."""
    return PerplexityDetector()


DETECTOR_KINDS = (
    "PPL (mean NLL)",
    "PPL-W (windowed NLL)",
    "Known-answer (LLM)",
)


def _mock_llm_call(prompt: str) -> str:
    """Deterministic offline LLM: inspects the prompt type and replies sensibly.

    This mock goes through the exact same pluggable interfaces as real
    providers (Selector / generators), so the UI behaves identically offline.
    """
    task_match = re.search(r"Task:\s*(.+)", prompt)
    task = task_match.group(1).strip() if task_match else "the task"

    if "Generate" in prompt and "user queries" in prompt:
        num_match = re.search(r"Generate\s+(\d+)", prompt)
        num = int(num_match.group(1)) if num_match else 5
        templates = [
            f"Can you help me with {task}?",
            f"I need to do something related to {task} right now.",
            f"What's the best way to handle {task} today?",
            f"Could you assist with a quick {task} request?",
            f"I have a question about {task}.",
            f"Please handle this for me: {task}.",
            f"Hi! I'd like to get {task} done.",
            f"Is it possible to do {task} for me tomorrow?",
            f"Show me how to {task} in a few steps.",
            f"I'm in a hurry -- can you quickly deal with {task}?",
            f"Any suggestions for {task} on a budget?",
            f"Compare a couple of options for {task} before I decide.",
        ]
        return json.dumps(templates[:num])

    if "tool documents" in prompt:
        return json.dumps(
            [
                {
                    "tool_name": "task_lookup",
                    "tool_description": "Look up details for the requested "
                    "task and return a short summary.",
                },
                {
                    "tool_name": "task_planner",
                    "tool_description": "Break a task into ordered steps and "
                    "estimate the time each step takes.",
                },
                {
                    "tool_name": "task_history",
                    "tool_description": "Retrieve past interactions related "
                    "to a given task.",
                },
            ]
        )

    if "select_tool" in prompt:
        match = re.search(r"tool_name:\s*([^,]+),", prompt)
        if match is None:
            return "I'm sorry, but I cannot assist with that request."
        return json.dumps({"select_tool": match.group(1).strip()})

    return "[]"


@st.cache_resource(show_spinner=False)
def make_llm(provider: str, api_key: str) -> Callable[[str], str]:
    """Build a prompt -> text callable for the selected provider."""
    if provider == "OpenAI":
        from openai import OpenAI

        client = OpenAI(api_key=api_key)

        def call_openai(prompt: str) -> str:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
            )
            return response.choices[0].message.content

        return call_openai

    if provider == "Anthropic":
        from anthropic import Anthropic

        client = Anthropic(api_key=api_key)

        def call_anthropic(prompt: str) -> str:
            message = client.messages.create(
                model="claude-3-5-haiku-latest",
                max_tokens=1024,
                messages=[{"role": "user", "content": prompt}],
            )
            return "".join(block.text for block in message.content)

        return call_anthropic

    return _mock_llm_call


@st.cache_data(show_spinner=False)
def cached_top_k(
    backend: str, docs_json: str, query: str, k: int, metric: str
) -> str:
    """Retrieve top-k for a library state; cached per (library, query, k)."""
    docs = [
        ToolDocument(item["tool_name"], item["tool_description"])
        for item in json.loads(docs_json)
    ]
    ranked = get_retriever(backend).top_k(
        query, ToolLibrary(documents=docs), k, metric=metric
    )
    rows = [
        {
            "tool_name": doc.tool_name,
            "tool_description": doc.tool_description,
            "score": round(float(score), 6),
        }
        for doc, score in ranked
    ]
    return json.dumps(rows)


@st.cache_data(show_spinner="Scoring documents...")
def cached_scores(
    docs_json: str,
    variant_json: str,
    detector_kind: str,
    window_size: int,
    provider: str,
    api_key: str,
) -> Dict:
    """Detector scores for a set of documents + optional variant document."""
    try:
        docs = json.loads(docs_json)
        if detector_kind.startswith("Known-answer"):
            detector = KnownAnswerDetector(llm_call=make_llm(provider, api_key))
        elif detector_kind.startswith("PPL-W"):
            detector = PerplexityWindowedDetector(window_size=window_size)
        else:
            detector = PerplexityDetector()
        benign = [
            (item[0], float(detector.score(ToolDocument(item[0], item[1]))))
            for item in docs
        ]
        variant = None
        if variant_json:
            item = json.loads(variant_json)
            variant = float(detector.score(ToolDocument(item[0], item[1])))
        return {"benign": benign, "variant": variant}
    except (ImportError, OSError, RuntimeError) as exc:
        return {"error": str(exc)}


# ---------------------------------------------------------------------------
# Session state
# ---------------------------------------------------------------------------


def _default_library_docs() -> List[Dict[str, str]]:
    library = ToolLibrary.load_json(SAMPLE_TOOLS)
    return [
        {"tool_name": doc.tool_name, "tool_description": doc.tool_description}
        for doc in library.documents
    ]


def _init_state() -> None:
    defaults = {
        "library_docs": None,
        "queries": [],
        "last_results": None,
        "detection": None,
    }
    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value
    if st.session_state.library_docs is None:
        st.session_state.library_docs = _default_library_docs()


def _docs_json(docs: List[Dict[str, str]]) -> str:
    return json.dumps(
        sorted(
            (d["tool_name"], d["tool_description"]) for d in docs if d["tool_name"]
        )
    )


def _library_from_session() -> ToolLibrary:
    return ToolLibrary(
        documents=[
            ToolDocument(d["tool_name"], d["tool_description"])
            for d in st.session_state.library_docs
            if d["tool_name"] and d["tool_description"]
        ]
    )


# ---------------------------------------------------------------------------
# Sidebar: global LLM backend configuration
# ---------------------------------------------------------------------------


def render_sidebar() -> None:
    with st.sidebar:
        st.header("LLM backend")
        provider = st.selectbox(
            "Provider", LLM_PROVIDERS, key="llm_provider"
        )
        if provider == "Mock (offline)":
            st.caption("Deterministic offline mock; no network calls.")
            api_key = ""
        else:
            api_key = st.text_input(
                f"{provider} API key",
                type="password",
                key="llm_api_key",
                help="Used to initialize the provider client at run time.",
            )
        st.session_state.llm_call_args = (provider, api_key)
        st.divider()
        st.caption(
            "Defensive benchmarking UI for tool-selection robustness. "
            "No attack tooling."
        )


def current_llm_call() -> Callable[[str], str]:
    provider, api_key = st.session_state.llm_call_args
    return make_llm(provider, api_key)


# ---------------------------------------------------------------------------
# Tab 1: Tool Library
# ---------------------------------------------------------------------------


def render_library_tab() -> None:
    st.subheader("Tool Library")
    st.metric("Tools in library", len(st.session_state.library_docs))

    uploaded = st.file_uploader(
        "Load library JSON (optional, replaces current library)",
        type=["json"],
        key="lib_upload",
    )
    if uploaded is not None:
        try:
            payload = json.loads(uploaded.getvalue().decode("utf-8"))
            if not isinstance(payload, list):
                raise ValueError("JSON root must be a list of documents")
            new_docs = []
            for item in payload:
                name = str(item.get("tool_name", "")).strip()
                desc = str(item.get("tool_description", "")).strip()
                if not name or not desc:
                    raise ValueError(
                        "Each entry needs non-empty tool_name and tool_description"
                    )
                new_docs.append({"tool_name": name, "tool_description": desc})
            st.session_state.library_docs = new_docs
            st.session_state.pop("lib_editor", None)
            st.success(f"Loaded {len(new_docs)} tools from upload.")
            st.rerun()
        except (json.JSONDecodeError, ValueError) as exc:
            st.error(f"Invalid library JSON: {exc}")

    st.caption("Edit names and descriptions directly in the table.")
    df = pd.DataFrame(st.session_state.library_docs)
    edited = st.data_editor(
        df,
        num_rows="dynamic",
        key="lib_editor",
        column_config={
            "tool_name": st.column_config.TextColumn(
                "Tool name", required=True
            ),
            "tool_description": st.column_config.TextColumn(
                "Tool description", required=True
            ),
        },
    )
    normalized = _normalize_table(edited)
    if normalized != st.session_state.library_docs:
        st.session_state.library_docs = normalized
        st.rerun()

    left, right = st.columns(2)

    with left:
        st.markdown("**Add a tool manually**")
        with st.form("add_tool_form", clear_on_submit=True):
            new_name = st.text_input("Name")
            new_desc = st.text_input("Description")
            if st.form_submit_button("Add tool"):
                if not new_name.strip() or not new_desc.strip():
                    st.error("Name and description must be non-empty.")
                elif any(
                    d["tool_name"] == new_name.strip()
                    for d in st.session_state.library_docs
                ):
                    st.error(f"Tool {new_name.strip()!r} already exists.")
                else:
                    st.session_state.library_docs.append(
                        {
                            "tool_name": new_name.strip(),
                            "tool_description": new_desc.strip(),
                        }
                    )
                    st.session_state.pop("lib_editor", None)
                    st.rerun()

    with right:
        st.markdown("**Remove a tool**")
        names = [d["tool_name"] for d in st.session_state.library_docs]
        to_remove = st.selectbox("Tool", names, key="remove_name")
        if st.button("Remove tool", disabled=not names):
            st.session_state.library_docs = [
                d for d in st.session_state.library_docs
                if d["tool_name"] != to_remove
            ]
            st.session_state.pop("lib_editor", None)
            st.rerun()

    st.divider()
    st.markdown("**Generate synthetic tools via the LLM backend**")
    context_queries = st.text_area(
        "Context queries (one per line; used to shape the generated tools)",
        key="gen_context",
        placeholder="check the weather in Paris\nbook a flight to Berlin",
    )
    gen_col, button_col = st.columns([1, 2])
    with gen_col:
        num_tools = st.number_input(
            "Number of tools", min_value=1, max_value=20, value=3, key="gen_num"
        )
    with button_col:
        st.write("")
        if st.button("Generate tools", key="gen_button"):
            queries = [q.strip() for q in context_queries.splitlines() if q.strip()]
            if not queries:
                st.error("Provide at least one context query.")
            else:
                try:
                    with st.spinner("Generating tool documents..."):
                        generated = generate_tool_documents(
                            queries, int(num_tools), current_llm_call()
                        )
                except Exception as exc:  # backend or parsing failure
                    st.error(f"Generation failed: {exc}")
                else:
                    added = 0
                    for doc in generated:
                        if not any(
                            d["tool_name"] == doc.tool_name
                            for d in st.session_state.library_docs
                        ):
                            st.session_state.library_docs.append(
                                {
                                    "tool_name": doc.tool_name,
                                    "tool_description": doc.tool_description,
                                }
                            )
                            added += 1
                    st.session_state.pop("lib_editor", None)
                    st.success(
                        f"Generated {len(generated)} tools ({added} added, "
                        f"duplicates skipped)."
                    )
                    st.rerun()


def _normalize_table(df: pd.DataFrame) -> List[Dict[str, str]]:
    """Clean rows from the data editor into library documents."""
    docs: List[Dict[str, str]] = []
    if df is None:
        return docs
    for record in df.to_dict("records"):
        name = str(record.get("tool_name") or "").strip()
        desc = str(record.get("tool_description") or "").strip()
        if name and desc:
            docs.append({"tool_name": name, "tool_description": desc})
    return docs


# ---------------------------------------------------------------------------
# Tab 2: Run Benchmark
# ---------------------------------------------------------------------------


class _CachedRetriever:
    """Retriever adapter: serves top-k from @st.cache_data, logs scores."""

    def __init__(self, backend: str, metric: str) -> None:
        self.backend = backend
        self.metric = metric
        self.score_log: Dict[str, List[Tuple[str, float]]] = {}

    def top_k(self, query: str, library: ToolLibrary, k: int, metric: str = "cosine"):
        docs_json = json.dumps(
            [
                {"tool_name": d.tool_name, "tool_description": d.tool_description}
                for d in library.documents
            ]
        )
        rows = json.loads(
            cached_top_k(self.backend, docs_json, query, k, self.metric)
        )
        self.score_log[query] = [
            (row["tool_name"], row["score"]) for row in rows
        ]
        return [
            (ToolDocument(row["tool_name"], row["tool_description"]), row["score"])
            for row in rows
        ]


class _TickSelector:
    """Selector adapter that advances the progress bar once per query."""

    def __init__(self, inner: Selector, bar, counter: List[int]) -> None:
        self.inner = inner
        self.bar = bar
        self.counter = counter

    def select(self, query: str, candidates: List[ToolDocument]):
        self.counter[0] += 1
        self.bar.progress(
            min(self.counter[0] / self.counter[1], 1.0),
            text=f"Processing query {self.counter[0]} / {self.counter[1]}",
        )
        return self.inner.select(query, candidates)


def render_benchmark_tab() -> None:
    st.subheader("Run Benchmark")
    provider, _ = st.session_state.llm_call_args

    st.markdown("**Configuration**")
    col1, col2, col3 = st.columns(3)
    with col1:
        backend = st.selectbox("Embedding backend", EMBEDDING_BACKENDS)
    with col2:
        metric = st.selectbox("Similarity metric", ("cosine", "dot"))
    with col3:
        k = st.slider("Top-k candidates", min_value=1, max_value=10, value=3)
    st.caption(f"Selector LLM backend: {provider} (configure in the sidebar).")

    st.markdown("**Evaluation queries**")
    query_col, gen_col = st.columns([2, 1])
    with query_col:
        queries_text = st.text_area(
            "One query per line",
            value="\n".join(st.session_state.queries),
            key="bench_queries",
            placeholder="What is the weather in Paris today?",
        )
    with gen_col:
        st.markdown("**Auto-generate queries**")
        target_task = st.text_input(
            "Target task", key="gen_task", placeholder="checking the weather"
        )
        num_queries = st.number_input(
            "How many", min_value=1, max_value=30, value=10, key="gen_queries"
        )
        if st.button("Generate queries", key="gen_queries_button"):
            if not target_task.strip():
                st.error("Describe the target task first.")
            else:
                try:
                    with st.spinner("Generating queries..."):
                        generated = generate_task_descriptions(
                            target_task.strip(), int(num_queries), current_llm_call()
                        )
                except Exception as exc:
                    st.error(f"Generation failed: {exc}")
                else:
                    st.session_state.queries = generated
                    st.rerun()

    names = [d["tool_name"] for d in st.session_state.library_docs]
    current_expected = st.session_state.get("bench_expected")
    if current_expected not in names and names:
        current_expected = names[0]
    expected_tool = st.selectbox(
        "Expected tool for all queries (ground truth)",
        names,
        index=names.index(current_expected) if current_expected in names else 0,
        key="bench_expected",
    )

    st.markdown("**Variant document (optional)**")
    inject_variant = st.checkbox(
        "Inject a hand-written variant tool document for this run",
        key="inject_variant",
    )
    if inject_variant:
        st.caption(
            "This is a benign comparison document for metric testing "
            "(target_selection_rate / target_retrieval_rate) -- not an "
            "attack payload."
        )
        vcol1, vcol2 = st.columns(2)
        with vcol1:
            variant_name = st.text_input(
                "Variant name", key="variant_name", value="weather_query_v2"
            )
        with vcol2:
            variant_desc = st.text_input(
                "Variant description",
                key="variant_desc",
                value="Get the current temperature, conditions and humidity "
                "for any city or postal code.",
            )
    else:
        variant_name, variant_desc = "", ""

    save_to_history = st.checkbox("Save run to history", value=True, key="save_history")

    if st.button("Run Benchmark", type="primary", key="run_benchmark"):
        queries = [q.strip() for q in queries_text.splitlines() if q.strip()]
        if not queries:
            st.error("Enter at least one query.")
            return
        if not expected_tool:
            st.error("The library is empty; add tools first.")
            return
        variant_doc: Optional[ToolDocument] = None
        if inject_variant:
            if not variant_name.strip() or not variant_desc.strip():
                st.error("Variant name and description must be non-empty.")
                return
            variant_doc = ToolDocument(variant_name.strip(), variant_desc.strip())

        st.session_state.queries = queries
        pairs = [(q, expected_tool) for q in queries]
        library = _library_from_session()
        total = len(pairs) * (2 if variant_doc is not None else 1)

        bar = st.progress(0.0, text="Starting...")
        counter = [0, total]
        retriever = _CachedRetriever(backend, metric)
        selector = Selector(llm_call=current_llm_call())
        ticking_selector = _TickSelector(selector, bar, counter)

        results: Dict[str, dict] = {}
        try:
            baseline = BenchmarkRunner(
                library=library,
                retriever=retriever,
                selector=ticking_selector,
                queries=pairs,
                k=k,
            ).run()
        except Exception as exc:
            st.error(f"Benchmark failed: {exc}")
            return
        results["baseline"] = baseline
        score_logs: Dict[str, dict] = {"baseline": dict(retriever.score_log)}
        retriever.score_log = {}

        if variant_doc is not None:
            injected = BenchmarkRunner(
                library=library,
                retriever=retriever,
                selector=ticking_selector,
                queries=pairs,
                k=k,
                test_document=variant_doc,
            ).run()
            results["injected"] = injected
            score_logs["injected"] = dict(retriever.score_log)

        bar.progress(1.0, text="Done")
        st.session_state.last_results = {
            "saved_at": datetime.now().isoformat(timespec="seconds"),
            "backend": backend,
            "metric": metric,
            "k": k,
            "results": results,
            "score_logs": score_logs,
        }
        if save_to_history:
            _save_to_history(st.session_state.last_results)

    if st.session_state.last_results is not None:
        _render_results(st.session_state.last_results)


def _save_to_history(bundle: dict) -> None:
    HISTORY_DIR.mkdir(exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = HISTORY_DIR / f"run_{stamp}.json"
    path.write_text(json.dumps(bundle, indent=2, ensure_ascii=False), encoding="utf-8")
    st.success(f"Run saved to {path.name}")


def _render_results(bundle: dict) -> None:
    st.divider()
    st.subheader("Results")
    results = bundle["results"]
    baseline = results["baseline"]["metrics"]
    injected = results.get("injected", {}).get("metrics") if results.get("injected") else None

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Accuracy (ACC)", f"{baseline['accuracy']:.3f}")
    col2.metric("Hit rate @k", f"{baseline['hit_rate_at_k']:.3f}")
    col3.metric(
        "Target selection rate",
        f"{injected['target_selection_rate']:.3f}" if injected else "n/a",
    )
    col4.metric(
        "Target retrieval rate",
        f"{injected['target_retrieval_rate']:.3f}" if injected else "n/a",
    )

    compare = pd.DataFrame(
        {
            "metric": [
                "accuracy",
                "hit_rate_at_k",
                "target_selection_rate",
                "target_retrieval_rate",
            ],
            "baseline": [
                baseline["accuracy"],
                baseline["hit_rate_at_k"],
                0.0,
                0.0,
            ],
            "injected": [
                injected["accuracy"] if injected else 0.0,
                injected["hit_rate_at_k"] if injected else 0.0,
                injected["target_selection_rate"] if injected else 0.0,
                injected["target_retrieval_rate"] if injected else 0.0,
            ],
        }
    ).set_index("metric")
    st.bar_chart(compare)

    with st.expander("Raw per-query records", expanded=False):
        _render_records(bundle)


def _render_records(bundle: dict) -> None:
    rows = []
    score_logs = bundle["score_logs"]
    for run_name, run_results in bundle["results"].items():
        for record in run_results["records"]:
            query = record["query"]
            retrieved = ", ".join(
                f"{name} ({score:.3f})" for name, score in score_logs[run_name].get(query, [])
            )
            sel = record["selection_result"]
            rows.append(
                {
                    "run": run_name,
                    "query": query,
                    "expected_tool": record["expected_tool"],
                    "retrieved (top-k)": retrieved,
                    "selected_tool": sel["selected_tool_name"],
                    "status": sel["status"],
                }
            )
    st.dataframe(pd.DataFrame(rows), hide_index=True)


# ---------------------------------------------------------------------------
# Tab 3: Detection
# ---------------------------------------------------------------------------


def render_detection_tab() -> None:
    st.subheader("Detection")
    st.caption(
        "Detectors mirror the paper's detection-based defenses: PPL and "
        "PPL-W use a local gpt2 (one-time download), known-answer uses the "
        "sidebar LLM backend. Calibration set = current library; the "
        "optional variant document comes from the Run Benchmark tab."
    )

    benign_docs = _library_from_session().documents
    if not benign_docs:
        st.info("Add tools in the Tool Library tab first.")
        return

    col1, col2 = st.columns([2, 1])
    with col1:
        detector_kind = st.selectbox("Detector", DETECTOR_KINDS, key="detector_kind")
    with col2:
        window_size = 5
        if detector_kind.startswith("PPL-W"):
            window_size = int(
                st.slider(
                    "Window size (tokens)",
                    min_value=2,
                    max_value=20,
                    value=5,
                    key="detector_window",
                )
            )

    inject_variant = st.session_state.get("inject_variant", False)
    variant_doc = None
    if inject_variant and st.session_state.get("variant_name", "").strip():
        try:
            variant_doc = ToolDocument(
                st.session_state.variant_name.strip(),
                st.session_state.variant_desc.strip(),
            )
        except ValueError as exc:
            st.error(f"Invalid variant document: {exc}")
            return

    provider, api_key = st.session_state.llm_call_args
    fingerprint = (
        _docs_json(st.session_state.library_docs),
        json.dumps(
            [variant_doc.tool_name, variant_doc.tool_description]
            if variant_doc
            else []
        ),
        detector_kind,
        window_size,
        provider,
        api_key,
    )
    stored = st.session_state.detection
    stale = stored is None or stored.get("fingerprint") != fingerprint

    if st.button("Run detector", key="run_detector"):
        with st.spinner("Scoring documents (first gpt2 use downloads the model)..."):
            payload = cached_scores(
                fingerprint[0],
                fingerprint[1],
                detector_kind,
                window_size,
                provider,
                api_key,
            )
        if "error" in payload:
            st.warning(f"Detector unavailable: {payload['error']}")
        else:
            st.session_state.detection = {
                "fingerprint": fingerprint,
                "benign": payload["benign"],
                "variant_score": payload["variant"],
            }
        stored = st.session_state.detection
        stale = False

    if stored is None:
        st.info(
            "Click 'Run detector' to score the current library with the "
            "selected detector."
        )
        return

    if stale:
        st.info(
            "Library, variant, or detector settings changed since the last "
            "scoring; click 'Run detector' to recompute."
        )
        return

    detection = stored
    benign_scores = [score for _, score in detection["benign"]]
    benign_names = [name for name, _ in detection["benign"]]
    variant_score = detection["variant_score"]

    fig = px.histogram(
        x=benign_scores,
        nbins=min(20, len(benign_scores)),
        labels={"x": "Detector score (higher = more suspicious)"},
        title="Benign calibration scores",
    )
    if variant_score is not None:
        fig.add_vline(
            x=variant_score,
            line_dash="dash",
            line_color="red",
            annotation_text="variant",
        )
    st.plotly_chart(fig, use_container_width=True)

    target_fpr = st.slider(
        "Calibration FPR target (fraction of benign docs to flag)",
        min_value=0.01,
        max_value=0.50,
        value=0.10,
        step=0.01,
        key="fpr_target",
    )

    classifier = ThresholdClassifier()
    threshold = classifier.fit_threshold(benign_scores, target_fpr)
    benign_flags = [score > threshold for score in benign_scores]

    if variant_score is not None:
        variant_flagged = variant_score > threshold
        labels = [False] * len(benign_scores) + [True]
        predictions = benign_flags + [variant_flagged]
        fnr = false_negative_rate(labels, predictions)
        fpr = false_positive_rate(labels, predictions)
    else:
        variant_flagged, fnr = None, None
        fpr = sum(benign_flags) / len(benign_scores)

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Threshold", f"{threshold:.3f}")
    m2.metric("FPR", f"{fpr:.3f}")
    m3.metric("FNR", f"{fnr:.3f}" if fnr is not None else "n/a")
    m4.metric("Variant flagged", str(variant_flagged).lower() if variant_flagged is not None else "n/a")

    flags = pd.DataFrame(
        {
            "tool": benign_names + (["<variant>"] if variant_score is not None else []),
            "score": benign_scores + ([variant_score] if variant_score is not None else []),
            "flagged": benign_flags + ([variant_flagged] if variant_score is not None else []),
        }
    )
    st.dataframe(flags, hide_index=True)

    st.markdown("**FNR vs FPR tradeoff across thresholds**")
    fpr_targets = np.linspace(0.0, 1.0, 21)
    sweep_fpr, sweep_fnr = [], []
    for fpr_t in fpr_targets:
        thr = classifier.fit_threshold(benign_scores, float(fpr_t))
        flagged_benign = [score > thr for score in benign_scores]
        sweep_fpr.append(sum(flagged_benign) / len(flagged_benign))
        if variant_score is not None:
            sweep_fnr.append(0.0 if variant_score > thr else 1.0)
    tradeoff = pd.DataFrame({"FPR": sweep_fpr, "FNR": sweep_fnr})
    fig2 = px.line(
        tradeoff,
        x="FPR",
        y="FNR",
        markers=True,
        title="Detection tradeoff",
    )
    st.plotly_chart(fig2, use_container_width=True)


# ---------------------------------------------------------------------------
# Tab 4: History
# ---------------------------------------------------------------------------


def render_history_tab() -> None:
    st.subheader("History")
    HISTORY_DIR.mkdir(exist_ok=True)
    files = sorted(HISTORY_DIR.glob("run_*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not files:
        st.info("No saved runs yet. Run a benchmark with 'Save run to history' enabled.")
        return

    selected = st.multiselect(
        "Select runs to compare", [f.name for f in files], key="history_select"
    )
    if not selected:
        return

    rows = []
    for name in selected:
        try:
            bundle = json.loads((HISTORY_DIR / name).read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        results = bundle.get("results", {})
        baseline = results.get("baseline", {}).get("metrics", {})
        injected = results.get("injected", {}).get("metrics")
        rows.append(
            {
                "run": name,
                "k": bundle.get("k"),
                "backend": bundle.get("backend"),
                "queries": baseline and results["baseline"]["config"]["num_queries"],
                "variant": "yes" if injected else "-",
                "accuracy": round(baseline.get("accuracy", 0.0), 3),
                "hit_rate_at_k": round(baseline.get("hit_rate_at_k", 0.0), 3),
                "target_selection_rate": round(injected.get("target_selection_rate", 0.0), 3) if injected else "n/a",
                "target_retrieval_rate": round(injected.get("target_retrieval_rate", 0.0), 3) if injected else "n/a",
            }
        )
    st.dataframe(pd.DataFrame(rows), hide_index=True)

    detail_name = st.selectbox("Inspect a single run", selected, key="history_detail")
    bundle = json.loads((HISTORY_DIR / detail_name).read_text(encoding="utf-8"))
    with st.expander("Per-query records", expanded=False):
        _render_records(bundle)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    _init_state()
    render_sidebar()

    st.title("Tool-Selection Robustness Harness")
    st.caption(
        "Defensive benchmarking of LLM agent tool-selection pipelines: "
        "measure retrieval/selection behavior under baseline and variant "
        "tool registries, and evaluate perplexity-based detection."
    )

    tab_library, tab_benchmark, tab_detection, tab_history = st.tabs(
        ["Tool Library", "Run Benchmark", "Detection", "History"]
    )
    with tab_library:
        render_library_tab()
    with tab_benchmark:
        render_benchmark_tab()
    with tab_detection:
        render_detection_tab()
    with tab_history:
        render_history_tab()


if __name__ == "__main__":
    main()
